apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: postgres-aurora
  title: Create template array filed
  description: Template teste
  tags: 
    - plataforma
spec:
  owner: sre
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        # Você pode coletar dados de texto do usuário usando o tipo string. Aqui está o exemplo mais básico. Ele solicitará ao usuário um nome.
        name:
          type: string
        # Você pode solicitar ao usuário uma lista de entities de catálogo usando a opção ui:field: EntityPicker da seguinte forma:
        entity:
          type: string
          ui:field: EntityPicker
        # Owned entity picker : Alternativamente, se você quiser que o usuário selecione apenas as entidades que já possuem, você pode querer usar o OwnedEntityPicker.
        #ownedEntity:
        #  type: string
        #  ui:field: OwnedEntityPicker
        # Entity name picker : Se você quiser um pouco de validação quando o usuário inserir um nome de Entidade, poderá usar o EntityNamePicker. Isso impedirá que o usuário insira um nome de entidade que não seja um nome de entidade aceitável.
        ownedEntity:
          type: string
          ui:field: EntityNamePicker
        kubernetes_cluster:
          title: Name Kubernetes Cluster
          type: string
          description: Name of the cluster kubernetes
          enum: 
            - "stg-01"
            - "stg-03"
            - "stg-02"
        namespace:
          title: Namespace
          type: string
          description: Name of the namespace in Kubernetes Cluster
          #ui:field: EntityNamePicker
          #ui:autofocus: true
        postgres_cluster:
          title: Postgres Cluster Name
          type: string
          description: Unique name of the new Postgres Cluster
          #ui:field: EntityNamePicker
          #ui:autofocus: true
        
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{parameters.name}}
    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        targetPath: ./community
        url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Create new project: ${{parameters.name}}"
        branchName: create-${{parameters.name}}
        description: |
          # New project: ${{parameters.name}}

          ${{ parameters.description if parameters.description }}
        targetPath: ${{ parameters.targetPath if parameters.targetPath else parameters.name }}

  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        text: "Go to PR"