name: 'TESTE Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Approve pull request
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "This pull request has passed automated review."
